# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
ignore:
  - '*.xlsx'
  - '*.csv'
  - '*.md'
  - '*.onnx'
  - .gitignore
  - condarc
  - '*.txt'
  - '*.toml'
#warning:
#  - '*.html'
#  - '*.yaml'
#  - '*.yml'
