#!/usr/bin/env python3
# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""
Operator Performance Map

A class to load and query operator performance data from YAML files
generated by update_operator_lookup_table.py.
"""

from pathlib import Path
from typing import Dict, Optional, Tuple, Union

import yaml


class OperatorPerfMap:
    """
    Represents a mapping from (optype, precision, input_shape_0, input_shape_1) to msecs.

    The mapping is loaded from a YAML file generated by update_operator_lookup_table.py.
    """

    def __init__(self, yaml_file: Union[str, Path]):
        """
        Initialize the performance map by reading from a YAML file.

        Args:
            yaml_file: Path to the YAML file containing the performance mapping

        Raises:
            FileNotFoundError: If the YAML file does not exist
            yaml.YAMLError: If the YAML file cannot be parsed
            ValueError: If the YAML file has an invalid structure
        """
        yaml_path = Path(yaml_file)
        if not yaml_path.exists():
            raise FileNotFoundError(f"YAML file not found: {yaml_file}")

        with open(yaml_path, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)

        if not isinstance(data, list):
            raise ValueError(f"YAML file must contain a list, got {type(data)}")

        # Build the mapping: (optype, precision, input_shape_0, input_shape_1) -> msecs
        self._map: Dict[Tuple[str, str, Tuple[int, ...], Tuple[int, ...]], float] = {}

        for entry in data:
            if not isinstance(entry, dict):
                raise ValueError(f"Each entry must be a dict, got {type(entry)}")

            # Read optype field (with fallback to op_code for backward compatibility)
            optype = entry.get('optype', entry.get('op_code', ''))
            precision = entry.get('precision')
            input_shape_0 = entry.get('input_shape_0')
            input_shape_1 = entry.get('input_shape_1')
            msecs = entry.get('msecs')

            if not optype or precision is None or input_shape_0 is None or input_shape_1 is None or msecs is None:
                raise ValueError(f"Missing required fields in entry: {entry}")

            # Convert shapes to tuples if they're lists
            if isinstance(input_shape_0, list):
                input_shape_0 = tuple(input_shape_0)
            elif not isinstance(input_shape_0, tuple):
                raise ValueError(f"input_shape_0 must be a list or tuple, got {type(input_shape_0)}")

            if isinstance(input_shape_1, list):
                input_shape_1 = tuple(input_shape_1)
            elif not isinstance(input_shape_1, tuple):
                raise ValueError(f"input_shape_1 must be a list or tuple, got {type(input_shape_1)}")

            # Ensure optype and precision are strings and normalize to uppercase for case-insensitive matching
            optype = str(optype).upper()
            precision = str(precision).upper()

            # Ensure msecs is a float
            if not isinstance(msecs, (int, float)):
                raise ValueError(f"msecs must be a number, got {type(msecs)}")
            msecs = float(msecs)

            # Create the key (normalized to uppercase for case-insensitive matching)
            key = (optype, precision, input_shape_0, input_shape_1)
            self._map[key] = msecs

    def get_msecs(
        self,
        optype: str,
        precision: str,
        input_shape_0: Union[Tuple[int, ...], list],
        input_shape_1: Union[Tuple[int, ...], list],
    ) -> Optional[float]:
        """
        Get the msecs value for the given operator type, precision and input shapes.
        Matching is case-insensitive for optype and precision.

        Args:
            optype: The operator type (e.g., "Matmul", "Add")
            precision: The precision/datatype (e.g., "BFLOAT16")
            input_shape_0: First input shape as a tuple or list of integers
            input_shape_1: Second input shape as a tuple or list of integers

        Returns:
            The msecs value if found, None otherwise
        """
        # Normalize inputs - convert to uppercase for case-insensitive matching
        optype = str(optype).upper()
        precision = str(precision).upper()
        if isinstance(input_shape_0, list):
            input_shape_0 = tuple(input_shape_0)
        if isinstance(input_shape_1, list):
            input_shape_1 = tuple(input_shape_1)

        # Create the lookup key (normalized to uppercase, matching how keys are stored)
        key = (optype, precision, input_shape_0, input_shape_1)

        # Direct dictionary lookup - O(1) instead of O(n)
        return self._map.get(key)

    def __len__(self) -> int:
        """Return the number of entries in the map."""
        return len(self._map)

    def __contains__(self, key: Tuple[str, str, Tuple[int, ...], Tuple[int, ...]]) -> bool:
        """Check if a key exists in the map."""
        return key in self._map

    def keys(self):
        """Return all keys in the map."""
        return self._map.keys()

    def values(self):
        """Return all values in the map."""
        return self._map.values()

    def items(self):
        """Return all (key, value) pairs in the map."""
        return self._map.items()

