# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
workloads:
  - api: TTNN
    name: addtensor
    basedir: workloads/ttnn
    module : run_ttnn_add_tensors@ttnn_add_tensors.py
    instances:
      default: { bs: 1 }
