ipblocks:
    -   name: nvidia_sm
        iptype: compute
        pipes:
        -   name: vector
            num_units: 64
            freq_MHz : 1410
            instructions:
            - {name: mac,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: add,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: sub,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: mul,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: div,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: tanh,  tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: log,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: exp,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: rsqrt, tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: cmp,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: mov,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
            - {name: max,   tpt: {int32: 1., int16: 1., int8: 4., bf16: 2., fp16: 2., fp32: 1., fp64: 0.5 }}
        -   name: matrix
            num_units: 4
            freq_MHz: 1410
            systolic_depth: 8
            instructions  :
            - {name: mac, tpt: { int4: 128.0, int8: 64.0, fp8: 64.0, bf16: 32.0, fp16: 32.0, tf32: 16.0, fp32: 0.0, fp64: 2.0}}
            - {name: add, tpt: { int4: 128.0, int8: 64.0, fp8: 64.0, bf16: 32.0, fp16: 32.0, tf32: 16.0, fp32: 0.0, fp64: 2.0}}
    -   name: tensix  # neo config
        iptype: compute
        l2_cache:
            num_banks: 64
            bytes_per_clk_per_bank: 64
        pipes:
        -   name: matrix
            num_units   : 4
            freq_MHz    : 1000
            instructions:
            -   {name: add, tpt: { int8: 2048, bf16: 512, fp16: 512, fp8: 2048,}}
            -   {name: sub, tpt: { int8: 2048, bf16: 512, fp16: 512, fp8: 2048,}}
            -   {name: mul, tpt: { int8: 2048, bf16: 512, fp16: 512, fp8: 2048,}}
            -   {name: mac, tpt: { int8: 2048, bf16: 512, fp16: 512, fp8: 2048,}}
        -   name: vector
            num_units   : 4
            freq_MHz    : 1000
            instructions:
            -   {name: add,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: sub,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: mul,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: div,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: mac,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: tanh,  tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: log,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: exp,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: rsqrt, tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: cmp,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: mov,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}
            -   {name: max,   tpt: {int8: 128.,  int32: 32., fp32: 32. }}


    -   name: gddr6
        iptype: memory
        technology: GDDR
        data_bits : 32
        data_rate : 8
        freq_MHz  : 1250
        size_GB   : 4
    -   name: gddr7
        iptype: memory
        technology: GDDR
        data_bits : 32
        data_rate : 16
        freq_MHz  : 1250
        size_GB   : 2
    -   name: hbm1
        iptype: memory
        technology: HBM
        freq_MHz  : 500
        stacks    : 8
        data_bits : 128
        size_GB   : 4
    -   name: hbm2
        iptype: memory
        technology: HBM
        freq_MHz  : 1200
        stacks    : 8
        data_bits : 128
        size_GB   : 8
    -   name: hbm2e
        iptype: memory
        technology: HBM
        freq_MHz  : 1800
        stacks    : 8
        data_bits : 128
        size_GB   : 16
    -   name: hbm3
        iptype: memory
        technology: HBM
        freq_MHz  : 3200
        stacks    : 16
        data_bits : 64
        size_GB   : 16
    -   name: hbm3e
        iptype: memory
        technology: HBM
        freq_MHz  : 4900
        stacks    : 16
        data_bits : 64
        size_GB   : 48
    -   name: hbm4
        iptype: memory
        technology: HBM
        freq_MHz  : 3200
        stacks    : 32
        data_bits : 64
        size_GB   : 64

packages:
    -   name: Grendel
        instances:
        -   name: Q1_S1
            ipgroups:
            -   ipname: tensix
                iptype: compute
                num_units   : 32
                ramp_penalty: 50
            -   ipname: gddr7
                iptype: memory
                num_units: 8
        -   name: Q1_A1
            ipgroups:
            -   ipname: tensix
                iptype:  compute
                num_units : 32
                freq_MHz  : 1200
                ramp_penalty: 50
            -   ipname: gddr7
                iptype: memory
                num_units: 16
                freq_MHz : 1250
        -   name: Q2_A2
            ipgroups:
            -   ipname: tensix
                iptype: compute
                num_units : 64
                freq_MHz  : 1200
                ramp_penalty: 100
            -   ipname: gddr7
                iptype: memory
                num_units: 24
                freq_MHz : 1250
    -   name: NvidiaGPU
        instances:
        -   name: A100
            ipgroups:
            -   ipname: nvidia_sm
                iptype: compute
                num_units     : 108
                ramp_penalty  : 100
                ip_overrides:
                    pipes.matrix.freq_MHz: 1410
                    pipes.vector.freq_MHz: 1410
                    pipes.matrix.instructions.mac.tpt.fp8: 0.0
                    pipes.vector.instructions.mac.tpt.bf16: 4.0
                    pipes.vector.instructions.mac.tpt.fp16: 4.0
            -   ipname: hbm2
                iptype: memory
                num_units: 5
                ip_overrides:
                    freq_MHz: 1215
        -   name: H100-SXM5
            ipgroups:
            -   ipname: nvidia_sm
                iptype: compute
                num_units   : 132
                ramp_penalty: 200
                ip_overrides:
                    pipes.matrix.freq_MHz: 1830
                    pipes.vector.freq_MHz: 1980
                    pipes.vector.num_units: 128
                    pipes.matrix.systolic_depth: 16
                    pipes.vector.instructions.mac.tpt.fp16: 2.0
            -   ipname: hbm3
                iptype: memory
                num_units: 5
                ip_overrides:
                    freq_MHz: 2619
        -   name: H200-SXM5
            ipgroups:
            -   ipname: nvidia_sm
                iptype: compute
                num_units   : 132
                ramp_penalty: 200
                ip_overrides:
                    pipes.matrix.freq_MHz: 1830
                    pipes.vector.freq_MHz: 1980
                    pipes.vector.num_units: 128
                    pipes.matrix.systolic_depth: 16
                    pipes.vector.instructions.mac.tpt.fp16: 2.0
            -   ipname: hbm3
                iptype: memory
                num_units: 6
                ip_overrides:
                    freq_MHz: 3200
                    stacks    : 16
                    data_bits : 64
                    size_GB   : 24
        -   name: H100-PCIe
            ipgroups:
              - ipname: nvidia_sm
                iptype: compute
                num_units   : 114
                ramp_penalty: 200
                ip_overrides:
                    pipes.matrix.freq_MHz: 1620
                    pipes.vector.freq_MHz: 1755
                    pipes.vector.num_units: 128
                    pipes.matrix.systolic_depth: 16
                    pipes.vector.instructions.mac.tpt.fp16: 2.0
              - ipname: hbm3
                iptype: memory
                num_units: 5
                ip_overrides:
                    freq_MHz: 1593
        -   name: L40-PCIe
            ipgroups:
            -   ipname: nvidia_sm
                iptype: compute
                num_units   : 142
                ramp_penalty: 50
                ip_overrides:
                    pipes.matrix.freq_MHz: 2490
                    pipes.vector.freq_MHz: 2490
                    pipes.vector.num_units: 128
                    pipes.matrix.systolic_depth: 2
                    pipes.matrix.instructions.mac.tpt.fp64: 0.0
                    pipes.vector.instructions.mac.tpt.fp16: 0.0
                    pipes.vector.instructions.mac.tpt.fp64: 0.0
                    pipes.vector.instructions.mac.tpt.fp16: 0.0
                    pipes.vector.instructions.mac.tpt.bf16: 0.0
            -   ipname: gddr6
                iptype: memory
                num_units: 12
                ip_overrides:
                    freq_MHz: 1125
        -   name: L4-PCIe
            ipgroups:
            -   ipname          : nvidia_sm
                iptype: compute
                num_units   : 58
                systolic_depth: 4
                ramp_penalty: 10
                ip_overrides:
                    pipes.matrix.freq_MHz: 2040
                    pipes.vector.freq_MHz: 2040
                    pipes.vector.num_units: 128
                    pipes.matrix.systolic_depth: 8
                    pipes.matrix.instructions.mac.tpt.fp64: 0.0
                    pipes.vector.instructions.mac.tpt.fp16: 0.0
                    pipes.vector.instructions.mac.tpt.fp64: 0.0
                    pipes.vector.instructions.mac.tpt.fp16: 0.0
                    pipes.vector.instructions.mac.tpt.bf16: 0.0
            -   ipname: gddr6
                iptype:   memory
                num_units: 6
                ip_overrides:
                  freq_MHz: 781.25
