workloads:
  - api: TTSIM
    name: YOLOv7
    basedir: workloads
    module : YOLO7@YOLO_v7.py
    instances:
      yolov7-tiny      : {yaml_cfg_path: 'https://raw.githubusercontent.com/WongKinYiu/yolov7/refs/heads/main/cfg/deploy/yolov7-tiny.yaml',      in_channels: 3, in_resolution: 640, bs: 1}
      yolov7-tiny-silu : {yaml_cfg_path: 'https://raw.githubusercontent.com/WongKinYiu/yolov7/refs/heads/main/cfg/deploy/yolov7-tiny-silu.yaml', in_channels: 3, in_resolution: 640, bs: 1}
      yolov7           : {yaml_cfg_path: 'https://raw.githubusercontent.com/WongKinYiu/yolov7/refs/heads/main/cfg/deploy/yolov7.yaml',           in_channels: 3, in_resolution: 640, bs: 1}
      yolov7x          : {yaml_cfg_path: 'https://raw.githubusercontent.com/WongKinYiu/yolov7/refs/heads/main/cfg/deploy/yolov7x.yaml',          in_channels: 3, in_resolution: 640, bs: 1}

  - api: TTSIM
    name: YOLOv8
    basedir: workloads
    module : YOLO8@Yolo_v8.py
    instances:
      yolov8s          : {yaml_cfg_path: 'https://raw.githubusercontent.com/autogyro/yolo-V8/refs/heads/main/ultralytics/models/v8/yolov8s.yaml', in_channels: 3, in_resolution: 640, bs: 1}
      yolov8n          : {yaml_cfg_path: 'https://raw.githubusercontent.com/autogyro/yolo-V8/refs/heads/main/ultralytics/models/v8/yolov8n.yaml', in_channels: 3, in_resolution: 640, bs: 1}
      yolov8m          : {yaml_cfg_path: 'https://raw.githubusercontent.com/autogyro/yolo-V8/refs/heads/main/ultralytics/models/v8/yolov8m.yaml', in_channels: 3, in_resolution: 640, bs: 1}
      # yolov8l          : {yaml_cfg_path: 'https://raw.githubusercontent.com/autogyro/yolo-V8/refs/heads/main/ultralytics/models/v8/yolov8l.yaml', in_channels: 3, in_resolution: 640, bs: 1}
      # yolov8x          : {yaml_cfg_path: 'https://raw.githubusercontent.com/autogyro/yolo-V8/refs/heads/main/ultralytics/models/v8/yolov8x.yaml', in_channels: 3, in_resolution: 640, bs: 1}
      # yolov8x6         : {yaml_cfg_path: 'https://raw.githubusercontent.com/autogyro/yolo-V8/refs/heads/main/ultralytics/models/v8/yolov8x6.yaml', in_channels: 3, in_resolution: 640, bs: 1}

  - api: TTSIM
    name: RESNET50
    basedir: workloads
    module : ResNet@basicresnet.py
    params : {layers: [3,4,6,3], num_classes: 1000, num_channels: 3, use_adaptive_pool: true, init_stride: 4, bs: 1}
    instances:
      rn50_b1_hd : { img_height: 1024, img_width: 1024, }
      rn50_b1_uhd: { img_height: 2828, img_width: 2828, }

  - api: TTSIM
    name: BEVDepth
    basedir: workloads/bevdepth
    module : BaseBEVDepth@BEVDepth.py
    params :
      is_train_depth    : false
      training          : false
      num_cameras       : 1
      num_sweeps        : 2
      head_conf_yaml    : config/bevdepth_cfgs/bevdepth_head.yaml
      backbone_conf_yaml: config/bevdepth_cfgs/bevdepth_backbone.yaml
    instances:
      bevdepth_s : { img_height:   32, img_width:   32, img_channels: 3, bs: 1 }
      bevdepth_m : { img_height:  256, img_width:  256, img_channels: 3, bs: 1 }
      bevdepth_l : { img_height: 1024, img_width: 1024, img_channels: 3, bs: 1 }
