# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
# Run Configuration yaml file, to be used with polproj.py
title: Run vitoptim (optimized sharded ViT) workloads
study: runvitoptim
odir: __runvitoptim
wlspec: config/all_workloads.yaml
archspec: config/tt_wh.yaml
wlmapspec: config/wl2archmapping.yaml
filterwlg: TTNN
filterarch: n150
datatype: bf16
filterwl: vitoptim_patch_embeddings,vitoptim_embeddings,vitoptim_attention,vitoptim_intermediate,vitoptim_output,vitoptim_layer,vitoptim_encoder,vitoptim,vitoptim_device_perf,vitoptim_perf_report
dump_stats_csv: true
log_level: debug
