# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

name: Checkin Tests

on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      id: setup-miniforge
      with:
        miniforge-version: latest
        channels: conda-forge
        conda-remove-defaults: "true"
        activate-environment: poldevenv
        environment-file: envdev.yaml
        condarc-file: etc/condarc
        auto-activate-base: false
    - name: check-miniforge-config     # Ensure default channels are not being used
      run: |
        conda list
        conda config --show-sources
    - name: Run Unit and Coverage Tests
      run: | 
        coverage erase
        coverage run -m pytest --junitxml __ci/xml/junit.xml
        coverage combine
        coverage report 
        coverage html -d __ci/html/
        coverage xml -o __ci/xml/coverage.xml
    - name: Run Checkin Tests
      if: always()
      run: |
        python checkin_tests.py static workloads
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dist-wo-onnxdumps
        path: |
           .coverage
           __RUN_TESTS
           !__RUN_TESTS/**/*.onnx
    
    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
