name: Check licenses in source files

on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:
    branches:
      - main

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      id: setup-miniforge
      with:
        miniforge-version: latest
        channels: conda-forge
        conda-remove-defaults: "true"
        activate-environment: poldevenv
        environment-file: envdev.yaml
        condarc-file: etc/condarc
        auto-activate-base: false
    - name: check-miniforge-config     # Ensure default channels are not being used
      run: |
        conda list
        conda config --show-sources
    - name: Check license and copyright
      run: |
          python tools/spdxchecker.py --ignore .github/spdxchecker-ignore.yml --allowed-licenses Apache-2.0 --allowed-copyright "Tenstorrent AI ULC"
    - uses: enarx/spdx@master
      with:
        licenses: |-
          Apache-2.0